spring:
  application:
    name: transporatation-service
  datasource:
    url: jdbc:mysql://localhost:3306/affablebean
    username: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9000
